# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hoolev 
tagline:          'WiFi, Network, Coding'
description:      '<a href="http://weibo.com/hoolev" target="_blank">@hoolev</a>关注<a href="/tag/#WiFi">WiFi</a>，<a href="/category/#Node">NodeJS</a>以及<a href="/category/#Meteor">Meteor</a>。'
baseurl:          '/'
paginate:         5

author:
  name:           'Hoolev'
  url:            http://weibo.com/hoolev


github:
  repo:           https://github.com/hoolev/hoolev.github.com
  githubEditBaseURL: https://github.com/hoolev/hoolev.github.com/edit/master/
